apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
  namespace: service-test
spec:
  limits:
  - max:
      cpu: "100m"
      memory: 100Mi
    min:
      cpu: "50m"
      memory: "50Mi"
    default:
      cpu: "100m"
      memory: "100Mi"
    defaultRequest:
      cpu: "50m"
      memory: "50Mi"
    type: Container
