apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: service-test
spec:
  ports:
  - nodePort: 31783
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: service-example
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
