apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-host
  namespace: my-svc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 192.168.99.111.nip.io # minikube ip
    http:
      paths:
      - path: /bar
        backend:
          serviceName: my-nginx
          servicePort: 80